# If you select "Forrest", play the "Forest and Nature.mp3" file
alias: Stop Lullaby
trigger:
  platform: state
  entity_id: input_select.lullaby
  state: "Forrest"
  for:
    hours: 1
    minutes: 30
action:
  - service: input_select.select_option
    data:
      entity_id: input_select.lullaby
      option: "None"

